from pathlib import Path
from typing import Optional, Any

from transformers import AutoTokenizer
from docling.document_converter import DocumentConverter
from docling.chunking import HybridChunker

class FileProcessor:
    def __init__(
        self,
        output_folder_path: str | Path,
        dense_model: str = "BAAI/bge-small-en-v1.5",
        sparse_model: str = "Qdrant/bm25",
        qdrant_url: str = "http://localhost:6333",
    ) -> None:
        self.output_folder_path = Path(output_folder_path)
        self.dense_model = dense_model
        self.sparse_model = sparse_model
        self.qdrant_url = qdrant_url
        self.converter = DocumentConverter()
        self.tokenizer = AutoTokenizer.from_pretrained(self.dense_model)
        self.chunker = HybridChunker(
            tokenizer=self.tokenizer,
            max_tokens=1000,
            repeat_table_header=True,
        )

    def process_file(self, relevant_file: dict[str, str | Path]) -> None:
        """
            Process a file, convert it to markdown, split it into chunks, and
            build embedding payloads for each chunk.

            The method supports regular files and ``.url`` files. For ``.url`` files,
            the content is read as UTF-8 text and stored as markdown output before
            continuing with conversion.

            :param relevant_file: Metadata dictionary describing the file to process.
                Expected keys are:

                - ``file_path`` (Path): Path to the source file.
                - ``source`` (str | Path): Logical source identifier used for output path and metadata.
                - ``target`` (str): Target identifier stored in each chunk result.
                - ``url`` (str, optional): Optional URL metadata.
            :return: A list of dictionaries, one per chunk, containing source metadata,
                chunk text, heading information, dense/sparse embedding texts, optional
                URL, and extracted page number.
        """
        file_path = relevant_file["file_path"]

        output_path = self.output_folder_path / (str(relevant_file["source"]) + ".md")
        output_path.parent.mkdir(parents=True, exist_ok=True)

        if file_path.is_file() and file_path.suffix.lower() == ".url":
            try:
                content = file_path.read_text(encoding="utf-8")
                output_path.write_text(content, encoding="utf-8")
                file_path = output_path
            except UnicodeDecodeError:
                return

        docling_conversion = self.converter.convert(file_path)
        docling_document = docling_conversion.document

        markdown_output = docling_document.export_to_markdown()
        output_path.write_text(markdown_output, encoding="utf-8")

        chunks_iter = self.chunker.chunk(dl_doc=docling_document)

        def chunk_to_dict(chunk):
            source = relevant_file["source"]
            source_path = Path(source)
            source_parents = source_path.parts[:-1] 
            filename = source_path.stem
            headings = getattr(chunk.meta, "headings", []) or []

            prefix = f"The headings are: {' > '.join(headings)}." if headings else f"Title is {source_path.name}."
            tags = f"Tags are {str(source_parents)}."
            dense_embedding_text = f"{prefix}\n{tags}\nContent: {chunk.text}\n"

            sparse_embedding_text = f"{' '.join(source_parents)} {filename} {' '.join(headings)} {chunk.text}"


            return {
                "source": source,
                "target": relevant_file["target"],
                "headings": headings,
                "text": chunk.text,
                "dense_embedding_text": dense_embedding_text,
                "sparse_embedding_text": sparse_embedding_text,
                "url": relevant_file.get("url"),
                "page_number": get_chunk_page_number(chunk),
            }

        result = list(map(chunk_to_dict, list(chunks_iter)))
        return result

def get_chunk_page_number(chunk: Any) -> Optional[int]:
    """
    Extracts any available page number from a given Docling chunk.
    
    This function iterates through the document items within the chunk's
    metadata and inspects their provenance details to find a page number.
    
    :param chunk: The chunk object generated by a Docling chunker.
    :return: The first encountered page number, or None if the document has no pages.
    """
    if not hasattr(chunk, "meta") or not hasattr(chunk.meta, "doc_items"):
        return None

    for item in chunk.meta.doc_items:
        if hasattr(item, "prov"):
            for prov in item.prov:
                if hasattr(prov, "page_no") and prov.page_no is not None:
                    return prov.page_no
                    
    return None